name = "EBM_Pkg"
uuid = "62328733-1825-4cda-9d2e-641b398c2b1c"
authors = ["Daniel Pals <Daniel.Pals@tum.de>"]
version = "0.1.0"

[compat]
julia = "1.7.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
